inherit_gem:
  rubocop-shopify: rubocop.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.6

Gemspec/DevelopmentDependencies:
  Enabled: true

Minitest/LiteralAsActualArgument:
  Enabled: true
